version: "3.7"
services:
  discord_bot:
    container_name: "noscope_bot"
    build:
      context: .
      dockerfile: ./noscope/Dockerfile
    env_file: ./noscope/.env
    entrypoint: ["python", "main.py"]
    volumes:
      - ./logs:/usr/src/app/logs

  telegram_bot:
    container_name: "noscope_tb"
    build:
      context: .
      dockerfile: ./noscope/Dockerfile
    env_file: ./noscope/.env.debug
    entrypoint: ["python", "main_telegram.py"]
    volumes:
      - ./logs:/usr/src/app/logs
    links:
      - redis:redis

  redis:
    container_name: "noscope_redis"
    restart: always
    image: redis:latest
    expose:
      - "6379"

  mongodb:
    container_name: "noscope_mongo"
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: noscope
      MONGO_INTIDB_ROOT_USERNAME: root
      MONGO_INTIDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/noscopbotmongodb

volumes:
  mongodb_data_container:
